Repository MaxCDN/bootstrapcdn, pull requests merged in 2018-04, with the labels that each got.

#994 Add a link to https://www.w3.org/html/.
  views/_partials/csscode.pug
  views/_partials/jscode.pug
Labels: www

#997 Add Bootstrap v4.1.0.
  config/_config.yml
  public/twitter-bootstrap/4.1.0/css/bootstrap-grid.css
  public/twitter-bootstrap/4.1.0/css/bootstrap-grid.css.map
  public/twitter-bootstrap/4.1.0/css/bootstrap-grid.min.css
  public/twitter-bootstrap/4.1.0/css/bootstrap-grid.min.css.map
  public/twitter-bootstrap/4.1.0/css/bootstrap-reboot.css
  public/twitter-bootstrap/4.1.0/css/bootstrap-reboot.css.map
  public/twitter-bootstrap/4.1.0/css/bootstrap-reboot.min.css
  public/twitter-bootstrap/4.1.0/css/bootstrap-reboot.min.css.map
  public/twitter-bootstrap/4.1.0/css/bootstrap.css
  public/twitter-bootstrap/4.1.0/css/bootstrap.css.map
  public/twitter-bootstrap/4.1.0/css/bootstrap.min.css
  public/twitter-bootstrap/4.1.0/css/bootstrap.min.css.map
  public/twitter-bootstrap/4.1.0/js/bootstrap.bundle.js
  public/twitter-bootstrap/4.1.0/js/bootstrap.bundle.js.map
  public/twitter-bootstrap/4.1.0/js/bootstrap.bundle.min.js
  public/twitter-bootstrap/4.1.0/js/bootstrap.bundle.min.js.map
  public/twitter-bootstrap/4.1.0/js/bootstrap.js
  public/twitter-bootstrap/4.1.0/js/bootstrap.js.map
  public/twitter-bootstrap/4.1.0/js/bootstrap.min.js
  public/twitter-bootstrap/4.1.0/js/bootstrap.min.js.map
Labels: cdn, www

#1008 Improve `getExtension()` regex.
  tests/test_helper.js
Labels: on_hold

#1000 Refactor tests.
  tests/bootlint_test.js
  tests/bootstrap_legacy_test.js
  tests/bootswatch3_test.js
  tests/bootswatch4_test.js
  tests/data_test.js
  tests/fontawesome_legacy_test.js
  tests/fontawesome_test.js
  tests/functional_test.js
  tests/index_test.js
  tests/integrations_test.js
  tests/privacy_policy_test.js
  tests/showcase_test.js
  tests/test_helper.js
Labels: enhancement

#1016 Move main.js outside of HTML.
  config/_config.yml
  package-lock.json
  package.json
  views/_partials/loadjs.pug
Labels: www

#1023 Clean up `CONTENT_TYPE_MAP`.
  test/test_helper.js
Labels: in progress

#1053 Add a custom 404 page.
  app.js
  routes/index.js
  test/404_test.js
  views/404.pug
Labels: enhancement, www

#1049 Fix endpoint adding a trailing slash for URIs with extension.
  test/test_helpers.js
Labels: bug

#1064 Add About page
  .pug-lintrc.json
  app.js
  routes/index.js
  test/about_test.js
  views/_partials/footer.pug
  views/about.pug
Labels: enhancement, www

#1062 Add a script to update Bootstrap.
  package-lock.json
  package.json
  scripts/update_bootstrap.js
Labels: in progress
