Repository MaxCDN/bootstrapcdn, pull requests merged in 2018-05, with the labels that each got.

#1075 Move ads styling to JS.
  public/assets/css/style.css
  public/assets/js/main.js
  views/_partials/carbonads.pug
Labels: www

#1092 Add more info about authors.
  config/_config.yml
  views/about.pug
Labels: www

#1093 Handle theme's query edge case
  lib/helpers.js
  routes/index.js
Labels: bug

#1089 Add tests for redirects.
  test/redirects_test.js
  test/test_helpers.js
Labels: enhancement

#1088 Improve data tests.
  app.js
  lib/helpers.js
  package-lock.json
  package.json
  scripts/wp-plugin.js
  test/data_test.js
  test/test_helpers.js
Labels: enhancement

#1067 Tighten `content-encoding` tests
  test/functional_test.js
  test/test_helpers.js
Labels: bug, cdn

#1102 Breaking out configuration.
  .gitignore
  app.js
  bin/www.js
  config/_app.yml
  config/_extras.yml
  config/_files.yml
  config/index.js
  lib/helpers.js
  routes/appendLocals.js
  scripts/integrity.js
  scripts/update_bootswatch.js
  test/test_helpers.js
Labels: enhancement

#1139 Fix navbar's active class.
  routes/appendLocals.js
  views/_mixins.pug
Labels: bug, www
