Repository MaxCDN/bootstrapcdn, pull requests merged in 2020-10, with the labels that each got.

#1630 It's been real
  config/_app.yml
Labels: www

#1636 Regenerate package-lock.json
  package-lock.json
Labels: dependencies

#1635 Production release
  .github/dependabot.yml
  config/_app.yml
  package-lock.json
  package.json
  public/assets/js/main.js
Labels: production
